version: "3.7"
services:
    app:
        build:
            args:
                user: social-app
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: social-app
        container_name: laravel-social-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - social
    mysql:
        image: mysql:8.0
        container_name: social-app-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./docker-compose/mysql-data:/var/lib/mysql
            - ./docker-compose/mysql-initdb:/docker-entrypoint-initdb.d
        networks:
            - social
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: social-app-phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - social
    nginx:
        image: nginx:alpine
        container_name: social-app-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - social
networks:
    social:
        driver: bridge
